- package-lock.json
- package.json
- src/App.tsx
- src/components/Home.tsx
- src/components/LoginForm.tsx
- src/components/RegistrationForm.tsx
- src/index.tsx
- Created the user login form
- Created a home page
- Added routing to pages
> Create user login form

- package-lock.json
- package.json
- src/App.tsx
- src/components/LoginForm.tsx
- src/components/ProjectList.tsx
- src/components/ProjectListTopBar.tsx
- src/components/ProtectedRoute.tsx
- src/components/RegistrationForm.tsx
- Added private routing
- Added a query to the database to validate credentials
- Added an error message for invalid credentials
> Verify login credentials

- src/App.tsx
- src/components/AddProjectForm.tsx
- Created the requestion to add a project to the database
- Created an error message for when the project creation is failed
- Created a success message for when the project creation succeeds
> Create request to add project to database

- src/App.tsx
- src/components/ProjectList.tsx
- Created the logic to map projects to ProjectCards
> Created request to retrieve list of projects

- src/App.tsx
- src/components/AddProjectForm.tsx
- src/components/Home.tsx
- src/components/LoginForm.tsx
- src/components/ProjectCard.tsx
- src/components/ProjectList.tsx
- src/components/ProjectListTopBar.tsx
- src/components/ProtectedRoute.tsx
- src/components/RegistrationForm.tsx
- src/components/TextArea.tsx
- src/components/TextField.tsx
- src/contexts/ApiContext.tsx
* Formatted and added some types too
> Add React Context for Client & User

- src/App.tsx
- src/components/ChangePasswordForm.tsx
- src/components/ProjectList.tsx
- src/components/ProjectListTopBar.tsx
- Created the password change form
- Added the request to database to change password
- Added error checking
- Added error & success messages
> Create password change form

- src/components/ProjectListTopBar.tsx
I realized we already have the user in the context, so we can just use that instead of a fetch.
> Use context user instead of fetch

- src/components/ProjectList.tsx
> Fix ProjectList Idle Error

- src/components/KanbanBoard.tsx
- src/components/ProjectCard.tsx
- src/components/sideNavBar.tsx
- Also updated the projectCards so the pointer changes to cursor on hover
> Created a navigation sidebar

- src/App.tsx
- src/components/Home.tsx
- src/components/LoginForm.tsx
- src/util/index.ts
* When you login its nice to not have to login again if you refresh the page
> Persist User Login in Local Storage

- src/App.tsx
- src/components/AddEditProjectBase.tsx
- src/components/AddMemberModal.tsx
- src/components/AddProjectForm.tsx
- src/components/DeleteProjectModal.tsx
- src/components/EditProjectForm.tsx
- src/components/KanbanBoard.tsx
- src/components/KanbanTopBar.tsx
- src/components/LeaveProjectModal.tsx
- src/components/ProjectList.tsx
- src/components/ProjectMemberTable.tsx
- src/components/ProjectSettings.tsx
- src/components/RemoveMemberModal.tsx
- src/components/SettingsTopBar.tsx
- Created project settings button on Kanban top bar
- Created project settings page
- Created project members section, which is only visible to the project admin
- Created leave project button + logic, which is only available if user is not project admin
- Created delete project button + logic, which is only available to project admin
- Created buttons + logic to delete project members
closes #34 #35 #15 #12 #22 #23
> Create project settings page

- src/components/AddMilestoneForm.tsx
- src/components/AddTaskForm.tsx
- src/components/DateChooser.tsx
- src/components/KanbanBoard.tsx
- src/components/KanbanColumn.tsx
- src/components/KanbanItem.tsx
- src/components/KanbanTopBar.tsx
- src/contexts/ApiContext.tsx
- added a drop down for task/milestone
- created milestone kanban
- added edit milestone modal, with same fields as add milestone
- added delete milestone modal
closes #49 #50 #51 #52 #53 #54 #55
> Kanban for milstone

- src/components/KanbanBoard.tsx
- src/components/KanbanColumn.tsx
- src/components/KanbanItem.tsx
- added task update
- added task deletion
closes #69
closes #70
closes #71 
closes #72 
closes #73 
closes #74 
closes #75
> Kanban edit delete tasks

- src/App.tsx
- src/components/AddSprintForm.tsx
- src/components/DateChooser.tsx
- src/components/DateRangeChooser.tsx
- src/components/DeleteSprintModal.tsx
- src/components/EditSprintForm.tsx
- src/components/SideNavBar.tsx
- src/components/Sprint.tsx
- src/components/SprintsList.tsx
- src/components/SprintsTopBar.tsx
- src/contexts/ApiContext.tsx
- Created a page for viewing, adding, editing, and deleting sprints
> Create page to view sprints

- src/components/ChangePasswordForm.tsx
> Change Password Redirect

- src/components/KanbanBoard.tsx
* Redirect to projectlist if project is null,
* Rest of changes are autoformatter
> Add Kanban Redirect

- src/components/Sprint.tsx
> Display qa task in sprint

- package-lock.json
- package.json
- src/components/Dependencies.tsx
- src/components/KanbanBoard.tsx
- src/contexts/ApiContext.tsx
> Refactor Dependency UI & Add Qa Tasks

- src/components/Dependencies.tsx
https://github.com/yismailuofa/kraken-frontend/assets/59630201/3e021a4e-0466-4258-a884-bec962e5ccf4
Maybe this completes #95 ? Not sure what how much more work we need on this screen or if we offload the status to another screen?
cc @ElenaArnold @acl-24
> Add QATask Toggle

- src/components/KanbanBoard.tsx
- src/components/KanbanColumn.tsx
- src/components/KanbanItem.tsx
kanban filter on both task and milestone
closes #66
closes #67
closes #68
> Kanban filter

- src/components/KanbanBoard.tsx
- src/components/KanbanColumn.tsx
- src/components/KanbanItem.tsx
- Added QA Task to Kanban
closes #134
> Kanban QA Task

- src/components/AddMilestoneForm.tsx
- src/components/AddTaskForm.tsx
- src/components/KanbanItem.tsx
- src/components/RegistrationForm.tsx
- Added success message on successful registration and navigation to login page
- Added error message on unsuccessful registration
- Removed alerts used for debugging
> Added Error and Success Messages to Registration Page

- src/components/AddMemberModal.tsx
- src/components/AddSprintForm.tsx
- src/components/AddTaskForm.tsx
- src/components/DeleteProjectModal.tsx
- src/components/DeleteSprintModal.tsx
- src/components/Dependencies.tsx
- src/components/KanbanBoard.tsx
- src/components/KanbanColumn.tsx
- src/components/KanbanItem.tsx
- src/components/RemoveMemberModal.tsx
- src/components/SideBarWithHeader.tsx
- Update look of modals
- Consistent button naming
- Consistent color scheme
- Added priority and assignedTo to tasks and qa tasks
> Update UI for consistency
